{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from dask import compute, delayed\n",
    "from dask.distributed import Client\n",
    "c = Client('63.35.185.250:8786')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "def process(data):\n",
    "    return np.sum(data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "distributed.batched - INFO - Batched Comm Closed: in <closed TCP>: BrokenPipeError: [Errno 32] Broken pipe\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n",
      "tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://172.31.14.214:8786' processes=24 cores=96>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 1208, in _run\n",
      "    return self.callback()\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 900, in _heartbeat\n",
      "    self.scheduler_comm.send({'op': 'heartbeat-client'})\n",
      "  File \"/home/mike/anaconda3/lib/python3.6/site-packages/distributed/batched.py\", line 117, in send\n",
      "    raise CommClosedError\n",
      "distributed.comm.core.CommClosedError\n"
     ]
    }
   ],
   "source": [
    "inputs = [[1,2,3],[4,5,6],[7,8,9]]\n",
    "values = [delayed(process)(x) for x in inputs]\n",
    "\n",
    "results = compute(*values, scheduler='distributed')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
